// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/register": {
            "post": {
                "description": "Email과 Password를 받아 등록하고, 생성된 USER_ID를 반환합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "신규 사용자 등록 (ID 반환)",
                "parameters": [
                    {
                        "description": "회원가입 정보",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/chat/history/{userId}": {
            "get": {
                "description": "특정 유저의 최근 대화 10건을 가져와 AI 문맥으로 활용합니다.",
                "produces": [
                    "application/json"
                ],
                "summary": "최근 대화 내역 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.ChatLog"
                            }
                        }
                    }
                }
            }
        },
        "/chat/save-turn": {
            "post": {
                "description": "사용자의 질문과 AI의 답변을 하나의 트랜잭션으로 DB에 안전하게 기록합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "대화 세트(질문+답변) 동시 저장",
                "parameters": [
                    {
                        "description": "저장할 대화 세트",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.SaveChatTurnInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/config/active-pet": {
            "get": {
                "description": "CURRENT_ACTIVE_PET 테이블에 저장된 현재 활성 펫 ID를 반환합니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "현재 설정된 대상 펫 ID 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "CURRENT_ACTIVE_PET 테이블의 펫 ID를 업데이트합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "급여기 대상 펫 설정 (Active Pet 변경)",
                "parameters": [
                    {
                        "description": "설정할 대상 펫 정보",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.SetActivePetInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/foods": {
            "post": {
                "description": "사료의 영양 성분을 먼저 등록하고 생성된 food_id를 반환받습니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "사료 기초 정보 등록",
                "parameters": [
                    {
                        "description": "사료 상세 정보",
                        "name": "food",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.FoodRegistrationInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/foods/photo": {
            "post": {
                "description": "등록된 사료 ID에 분석용 사진 경로를 매핑합니다.",
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "사료 봉투 사진 업로드",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Food ID",
                        "name": "food_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Food Pack Photo",
                        "name": "photo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/iot/self-manual-weight": {
            "post": {
                "description": "이전 잔량을 무시하고 입력값을 저장하되, 동일한 시간의 중복 입력은 차단합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pets"
                ],
                "summary": "수동 급여 기록 저장",
                "parameters": [
                    {
                        "description": "수동 급여 데이터",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ManualFeedInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/iot/weight": {
            "post": {
                "description": "실시간 사료 잔량 데이터를 수신합니다. PETS에서 사료 ID를 선조회 후 로그 테이블에 정석 인서트하여 바인딩 오류를 해결합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IoT"
                ],
                "summary": "IoT 사료 무게 수신",
                "parameters": [
                    {
                        "description": "무게 데이터",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.IoTWeightInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/iot/weight-pair": {
            "delete": {
                "description": "입력한 급여 로그와 그 바로 다음에 기록된 섭취 완료 로그를 찾아 함께 삭제합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "급여 기록 쌍 삭제",
                "parameters": [
                    {
                        "description": "삭제 요청 데이터",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.DeleteFeedLogInput"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/logs/{logId}": {
            "delete": {
                "description": "LOG_ID를 기준으로 특정 사료 무게 로그를 삭제합니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logs"
                ],
                "summary": "특정 사료 로그 삭제",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "삭제할 로그의 LOG_ID",
                        "name": "logId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/pets": {
            "post": {
                "description": "새로운 반려동물을 등록하고 별도 테이블에 다중 건강 상태를 저장합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "반려동물 등록",
                "parameters": [
                    {
                        "description": "반려동물 등록 정보",
                        "name": "pet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.PetRegistrationInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/pets/food": {
            "put": {
                "description": "반려동물의 현재 사료(CURRENT_FOOD_ID)를 교체합니다. 과거 무게 로그의 사료 히스토리는 유지되며, 이후 적재되는 로그부터 새 사료 ID가 적용됩니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pets"
                ],
                "summary": "반려동물 사료 교체",
                "parameters": [
                    {
                        "description": "사료 교체 정보",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ChangeFoodInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":\"success\",\"message\":\"...\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "{\"error\":\"입력 데이터가 올바르지 않습니다.\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "{\"error\":\"존재하지 않는 반려동물 ID입니다.\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{\"error\":\"사료 정보 변경 중 오류가 발생했습니다.\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/pets/meal-details": {
            "post": {
                "description": "특정 급여 시간을 기준으로 사료명, 급여량, 실제 섭취량을 계산하여 반환합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "1회 급여량 및 섭취량 상세 조회",
                "parameters": [
                    {
                        "description": "급여 조회 요청 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.MealDetailsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.MealDetailsResponse"
                        }
                    }
                }
            }
        },
        "/pets/photo": {
            "post": {
                "description": "비만도 분석을 위한 사진을 업로드하고 DB에 경로를 저장합니다.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "반려동물 사진 업로드",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pet ID",
                        "name": "pet_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Pet Photo File",
                        "name": "photo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/pets/{id}": {
            "get": {
                "description": "AI 모듈이나 프론트엔드에서 반려동물의 현재 상태 및 다중 질병 목록을 가져옵니다.",
                "produces": [
                    "application/json"
                ],
                "summary": "반려동물 상세 정보 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "제공된 모든 필드 및 다중 질병 목록을 바탕으로 반려동물 정보를 최신화합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "반려동물 상세 정보 통합 수정",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "수정할 상세 데이터",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdatePetInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "pet_id를 이용해 해당 반려동물의 정보를 DB에서 영구 삭제합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "반려동물 정보 삭제",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/pets/{id}/analysis": {
            "patch": {
                "description": "비만도, 급여량과 함께 분석된 사료의 ID(FK)를 PETS 테이블에 저장합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "AI 분석 결과 통합 저장 (BCS + 급여량 + 사료 연결)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AI 분석 결과 (BCS, 추천급여량)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.AIAnalysisResultInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/pets/{id}/bcs": {
            "patch": {
                "description": "AI 분석 결과를 받아 반려동물의 BCS 점수와 분석 날짜를 최신화합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "반려동물 비만도(BCS) 업데이트",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "BCS 분석 결과",
                        "name": "bcs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.PetBCSUpdateInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/pets/{id}/consumption": {
            "get": {
                "description": "특정 날짜의 무게 변화를 분석하여 총 급여량, 섭취량, 잔량을 반환합니다. 수동 입력 데이터는 이전 잔량 차감 없이 입력값 그대로 누적하며, 잔량은 (총급여-총섭취)로 계산됩니다.",
                "tags": [
                    "Pets"
                ],
                "summary": "일일 총 섭취량 및 통계 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "조회 날짜 (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.DailyConsumptionResponse"
                        }
                    }
                }
            }
        },
        "/pets/{id}/food": {
            "patch": {
                "description": "지정된 반려동물의 현재 급여 사료(CURRENT_FOOD_ID)만 단독으로 변경합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pets"
                ],
                "summary": "반려동물 사료 단독 교체",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "새로운 사료 ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdateFoodInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/pets/{id}/monthly-consumption": {
            "get": {
                "description": "특정 월(YYYY-MM)의 일별 사료 무게 변화를 조회하여 통계 리스트를 반환합니다. 수동 입력 데이터는 잔량 차감 없이 입력값 그대로 반영되며, 잔량은 (총급여-총섭취)로 계산됩니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pets"
                ],
                "summary": "월간 일별 섭취율 및 통계 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "조회 월 (YYYY-MM)",
                        "name": "month",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.MonthlyConsumptionResponse"
                        }
                    }
                }
            }
        },
        "/pets/{id}/sessions": {
            "get": {
                "description": "특정 날짜의 사료 무게 로그를 분석하여 LOG_ID와 FEED_TYPE이 포함된 세션 타임라인을 반환합니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pets"
                ],
                "summary": "반려동물 회당 급여 및 섭취 목록 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "조회 날짜 (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.PetSessionListResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "이메일과 비밀번호를 검증하여 로그인을 처리하고 고유 USER_ID를 반환합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "사용자 로그인",
                "parameters": [
                    {
                        "description": "로그인 정보",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/password": {
            "put": {
                "description": "가입된 이메일을 조회하여 해당 사용자의 비밀번호를 새로운 비밀번호로 최신화합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "사용자 비밀번호 수정 (이메일 기준)",
                "parameters": [
                    {
                        "description": "비밀번호 변경 요청 데이터",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdatePasswordInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "delete": {
                "description": "사용자와 관련된 모든 데이터(반려동물, 로그 등)를 삭제하고 탈퇴 처리합니다.",
                "summary": "회원 탈퇴",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/{id}/pets": {
            "get": {
                "description": "특정 유저가 등록한 모든 반려동물의 리스트를 가져옵니다.",
                "produces": [
                    "application/json"
                ],
                "summary": "유저별 반려동물 목록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.AIAnalysisResultInput": {
            "type": "object",
            "properties": {
                "bcs": {
                    "type": "integer",
                    "example": 5
                },
                "food_id": {
                    "description": "분석 결과 식별된 사료 번호",
                    "type": "integer",
                    "example": 101
                },
                "recommended_amount": {
                    "type": "number",
                    "example": 150.5
                }
            }
        },
        "main.ChangeFoodInput": {
            "type": "object",
            "required": [
                "new_food_id",
                "pet_id"
            ],
            "properties": {
                "new_food_id": {
                    "type": "integer",
                    "example": 5
                },
                "pet_id": {
                    "type": "integer",
                    "example": 101
                }
            }
        },
        "main.ChatLog": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "main.DailyConsumptionResponse": {
            "type": "object",
            "properties": {
                "consumption_rate": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "log_count": {
                    "type": "integer"
                },
                "pet_id": {
                    "type": "integer"
                },
                "status_color": {
                    "type": "string"
                },
                "total_consumption": {
                    "type": "number"
                },
                "total_fed": {
                    "type": "number"
                },
                "total_remaining": {
                    "type": "number"
                }
            }
        },
        "main.DeleteFeedLogInput": {
            "type": "object",
            "properties": {
                "feed_amount": {
                    "type": "number",
                    "example": 100
                },
                "feed_time": {
                    "description": "YYYY-MM-DD HH24:MI:SS",
                    "type": "string",
                    "example": "2026-05-17 14:00:00"
                },
                "pet_id": {
                    "type": "integer",
                    "example": 166
                }
            }
        },
        "main.FeedingSessionElement": {
            "type": "object",
            "properties": {
                "consumed_amount": {
                    "description": "회당 섭취량 (g)",
                    "type": "number"
                },
                "current_food_id": {
                    "description": "해당 세션 당시의 사료 고유 ID",
                    "type": "integer"
                },
                "fed_amount": {
                    "description": "회당 급여량 (g)",
                    "type": "number"
                },
                "feed_type": {
                    "description": "[추가] 'AUTO' 또는 'MANUAL'",
                    "type": "string"
                },
                "feeding_time": {
                    "description": "급여 시작 시간 (YYYY-MM-DD HH24:MI:SS)",
                    "type": "string"
                },
                "food_name": {
                    "description": "[추가] 실제 사료 이름 (예: 로얄캐닌 닥터)",
                    "type": "string"
                },
                "log_id": {
                    "description": "[추가] 로그 고유 고유 ID",
                    "type": "integer"
                }
            }
        },
        "main.FoodRegistrationInput": {
            "type": "object",
            "properties": {
                "fat_pct": {
                    "type": "number",
                    "example": 13
                },
                "kcal_per_g": {
                    "type": "number",
                    "example": 3.85
                },
                "product_name": {
                    "type": "string",
                    "example": "로얄캐닌 인도어"
                },
                "protein_pct": {
                    "type": "number",
                    "example": 27.5
                }
            }
        },
        "main.IoTWeightInput": {
            "type": "object",
            "required": [
                "feed_weight",
                "pet_id"
            ],
            "properties": {
                "feed_weight": {
                    "description": "💡 변경점: float64 -\u003e *float64 로 변경하여 0.0 값을 허용하도록 처리",
                    "type": "number",
                    "example": 45.2
                },
                "pet_id": {
                    "description": "기기 할당 반려동물 ID",
                    "type": "integer",
                    "example": 126
                }
            }
        },
        "main.LoginInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "test@sunmoon.ac.kr"
                },
                "password": {
                    "type": "string",
                    "example": "password123!"
                }
            }
        },
        "main.ManualFeedInput": {
            "type": "object",
            "properties": {
                "consumption": {
                    "description": "섭취량 (g)",
                    "type": "number",
                    "example": 20
                },
                "feed_amount": {
                    "description": "급여량 (g)",
                    "type": "number",
                    "example": 23
                },
                "feed_time": {
                    "description": "YYYY-MM-DD HH24:MI:SS",
                    "type": "string",
                    "example": "2026-05-20 13:05:00"
                },
                "pet_id": {
                    "type": "integer",
                    "example": 166
                }
            }
        },
        "main.MealDetailsRequest": {
            "type": "object",
            "properties": {
                "feed_time": {
                    "description": "YYYY-MM-DD HH24:MI:SS 형식",
                    "type": "string",
                    "example": "2026-05-13 14:12:39"
                },
                "pet_id": {
                    "type": "integer",
                    "example": 166
                }
            }
        },
        "main.MealDetailsResponse": {
            "type": "object",
            "properties": {
                "consumption": {
                    "description": "1회 섭취량 (g)",
                    "type": "number"
                },
                "feed_amount": {
                    "description": "1회 급여량 (g)",
                    "type": "number"
                },
                "food_name": {
                    "description": "사료명",
                    "type": "string"
                }
            }
        },
        "main.MonthlyConsumptionElement": {
            "type": "object",
            "properties": {
                "consumption_rate": {
                    "description": "당일 섭취율 (%)",
                    "type": "number"
                },
                "date": {
                    "description": "날짜 (YYYY-MM-DD)",
                    "type": "string"
                },
                "status_color": {
                    "description": "상태 색상 (초록/노랑/빨강)",
                    "type": "string"
                },
                "total_consumption": {
                    "description": "당일 총 섭취량 (g)",
                    "type": "number"
                },
                "total_fed": {
                    "description": "[복구] 당일 총 급여량 (g)",
                    "type": "number"
                },
                "total_remaining": {
                    "description": "[복구] 당일 최종 잔량 (g)",
                    "type": "number"
                }
            }
        },
        "main.MonthlyConsumptionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.MonthlyConsumptionElement"
                    }
                },
                "month": {
                    "description": "조회 월 (YYYY-MM)",
                    "type": "string"
                },
                "pet_id": {
                    "type": "integer"
                }
            }
        },
        "main.PetBCSUpdateInput": {
            "type": "object",
            "required": [
                "bcs"
            ],
            "properties": {
                "bcs": {
                    "description": "1~9 사이의 비만도 점수",
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "main.PetRegistrationInput": {
            "type": "object",
            "properties": {
                "bcs_score": {
                    "description": "[추가] BCS 점수",
                    "type": "integer",
                    "example": 1
                },
                "birth_date": {
                    "type": "string",
                    "example": "2024-01-01"
                },
                "breed": {
                    "type": "string",
                    "example": "Poodle"
                },
                "current_weight": {
                    "type": "number",
                    "example": 7.5
                },
                "gender": {
                    "type": "string",
                    "example": "U"
                },
                "health_status": {
                    "description": "[수정] 문자열 배열로 변경",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "성공이"
                },
                "species": {
                    "type": "string",
                    "example": "Dog"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "main.PetSessionListResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "integer"
                },
                "session_count": {
                    "type": "integer"
                },
                "sessions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.FeedingSessionElement"
                    }
                }
            }
        },
        "main.RegisterInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "test@sunmoon.ac.kr"
                },
                "password": {
                    "type": "string",
                    "example": "pass1234"
                }
            }
        },
        "main.SaveChatTurnInput": {
            "type": "object",
            "required": [
                "ai_message",
                "user_id",
                "user_message"
            ],
            "properties": {
                "ai_message": {
                    "type": "string",
                    "example": "오늘 성공이는 총 120g을 먹었습니다."
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                },
                "user_message": {
                    "type": "string",
                    "example": "성공이 오늘 사료 얼마나 먹었어?"
                }
            }
        },
        "main.SetActivePetInput": {
            "type": "object",
            "required": [
                "pet_id"
            ],
            "properties": {
                "pet_id": {
                    "type": "integer"
                }
            }
        },
        "main.UpdateFoodInput": {
            "type": "object",
            "required": [
                "food_id"
            ],
            "properties": {
                "food_id": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "main.UpdatePasswordInput": {
            "type": "object",
            "required": [
                "email",
                "new_password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "test@sunmoon.ac.kr"
                },
                "new_password": {
                    "type": "string",
                    "example": "newPassword123!"
                }
            }
        },
        "main.UpdatePetInput": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "bcs_score": {
                    "type": "integer",
                    "example": 1
                },
                "birth_date": {
                    "description": "포맷 가이드 변경 (YYYY-MM-DD)",
                    "type": "string",
                    "example": "2024-01-01"
                },
                "breed": {
                    "type": "string",
                    "example": "Poodle"
                },
                "current_food_id": {
                    "type": "integer",
                    "example": 0
                },
                "current_weight": {
                    "type": "number",
                    "example": 7.5
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "M",
                        "F",
                        "U"
                    ],
                    "example": "U"
                },
                "health_status": {
                    "description": "수정: 단일 string에서 문자열 슬라이스로 변경",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "diabetes",
                        "arthritis"
                    ]
                },
                "name": {
                    "type": "string",
                    "example": "성공이"
                },
                "photo_url": {
                    "type": "string",
                    "example": ""
                },
                "recommended_feed_amount": {
                    "type": "number",
                    "example": 0
                },
                "rer_value": {
                    "type": "number",
                    "example": 317.24
                },
                "species": {
                    "type": "string",
                    "example": "Dog"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "PetFeed API Server",
	Description:      "반려동물 건강 관리 및 AI 분석 백엔드 서버입니다.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
